### ISSUE TITLE
crash when using with some other mods

### ISSUE THREAD

**Issue by FateRover** [Conquest-Reforged/ConquestReforged#182]
hi,I found it crashes the game when using this mod with some other mod,
here   just the  mod  list:

- Pam's HarvestCraft 1.12.2t.jar
- ConquestReforged-3.0.1-mc1.12.2.jar
- forestry_1.12.2-5.8.0.285.jar
- BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar
- binnie-mods-1.12.2-2.5.0.164.jar
- realworld-1.16.jar  
 if they were all  actived,game  crashes,  remove  any of them ,game wont.for  i down load your mod last,i think should  report here,actually i dont known which mod cause this.

here is the log create by a  launcher
win10 and forge 1.12.2-14.23.3.2678 java8

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/6/18 5:48 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:293)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:279)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:112)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:153)
	at com.pam.harvestcraft.blocks.BlockRegistry.onBlockRegistry(BlockRegistry.java:460)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_BlockRegistry_onBlockRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:293)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:279)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:112)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:153)
	at com.pam.harvestcraft.blocks.BlockRegistry.onBlockRegistry(BlockRegistry.java:460)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_BlockRegistry_onBlockRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 39843768 bytes (37 MB) / 555745280 bytes (530 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version                 | Source                                                        | Signature                                |
	|:----- |:------------- |:----------------------- |:------------------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft     | 1.12.2                  | minecraft.jar                                                 | None                                     |
	| UCH   | mcp           | 9.42                    | minecraft.jar                                                 | None                                     |
	| UCH   | FML           | 8.0.99.99               | forge-1.12.2-14.23.3.2678.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge         | 14.23.3.2678            | forge-1.12.2-14.23.3.2678.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | harvestcraft  | 1.12.2t                 | [1.12.2][丰收工艺(潘马斯农场)]Pam's+HarvestCraft+1.12.2t.jar           | None                                     |
	| UCH   | connect       | 1.0.3-mc1.12.2-SNAPSHOT | [1.12.2][征服者]ConquestReforged-3.0.1-mc1.12.2.jar              | None                                     |
	| UCH   | conquest      | 3.0.1                   | [1.12.2][征服者]ConquestReforged-3.0.1-mc1.12.2.jar              | None                                     |
	| UCH   | blockpalette  | 1.5.0                   | [1.12.2][征服者]ConquestReforged-3.0.1-mc1.12.2.jar              | None                                     |
	| UCH   | forestry      | 5.8.0.285               | [1.12.2][林业]forestry_1.12.2-5.8.0.285.jar                     | None                                     |
	| UCH   | realworld     | 1.16                    | [1.12.2][真实世界]realworld-1.16.jar                              | None                                     |
	| UCH   | biomesoplenty | 7.0.1.2387              | [1.12.2][超多生物群落]BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar | None                                     |
	| UCH   | binniecore    | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |
	| UCH   | binniedesign  | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |
	| UCH   | genetics      | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |
	| UCH   | botany        | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |
	| UCH   | extrabees     | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |
	| UCH   | extratrees    | 2.5.0.164               | [1.12][林业扩展]binnie-mods-1.12.2-2.5.0.164.jar                  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: HMCL 2.7.9.55
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest+Reforged.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
```

**Comment by HIPPOKLEIDES** [comment]
You're crashing because you've exceeded the limit of blocks Minecraft can handle at the moment (looks like it reached the limit at Pam's Harvestcraft). These IDs shouldn't be an issue in 1.13 as they're being removed entirely.

**Comment by FateRover** [comment]
thx  for reply，for  the  key  word  “exceeded  ids”，i search in  curse，and  find a  mod called “notenoughIDS ”.this mod  extends the ids limit,  i  think  maybe u  can  add it  as a suggested mod incase others face the problem

**Comment by dags-** [comment]
that mod would make worlds un-convertable going from 1.12 to 1.13, which would not be acceptable for many of our users
